stages:
  collect_data:
    cmd: python fetch_weather.py
    deps:
      - fetch_weather.py
    outs:
      - data/raw_data.csv
  preprocess_data:
    cmd: python preprocess_data.py
    deps:
      - preprocess_data.py
      - data/raw_data.csv
    outs:
      - data/processed_data.csv
  train_model:
    cmd: python train_model.py
    deps:
      - train_model.py
      - data/processed_data.csv
    outs:
      - models/model.pkl
